searchWorkOnSite {
	SELECT A.*
	FROM (
	    SELECT TW.ONSITEID, SU.USERID, TW.EMPLOYEEID, EM.FIRSTNAMETHA, EM.LASTNAMETHA, EM.NICKNAME
	        , TW.WORKONSITEID, TW.ONSITEDATEFROM1, TW.ONSITETIMEFROM1, TW.ONSITEDATETO2, TW.ONSITETIMETO2
	        , TW.TOTAL_ONSITEDAY, TW.TOTAL_ONSITETIME, TW.SITESERVICE, TW.ONSITESTATUS
	        , TW.APPROVERID, TW.APPROVETS, TW.SITESERVICE_REMARK, TW.ONSITESTATUS_REMARK 
	    FROM TAD_WORKONSITE TW 
	        LEFT JOIN EMP_MEMBER EM ON EM.EMPLOYEEID = TW.EMPLOYEEID
	        LEFT JOIN SEC_USER SU ON SU.EMPLOYEEID = EM.EMPLOYEEID
	    WHERE SU.USERID IS NOT NULL
	    	AND SU.STATUS <> 'I' -- ไม่เอา user ที่ลาออก
	    	AND TW.WORKONSITEID = 23 -- Fix ประเภทหยุดชดเชย
			AND TW.ONSITESTATUS IN ('A', 'W')
	        AND CASE WHEN TW.UPDATETS IS NOT NULL THEN TW.UPDATETS ELSE TW.INPUTTS END >= %s -- '20100101000000'
	    	AND SU.USERID = %s -- กรณีที่ต้องการดึงเป็นรายบุคคล        
	    UNION ALL
	    SELECT TW.ONSITEID, SU.USERID, TW.EMPLOYEEID, EM.FIRSTNAMETHA, EM.LASTNAMETHA, EM.NICKNAME
	        , TW.WORKONSITEID, TW.ONSITEDATEFROM1, TW.ONSITETIMEFROM1, TW.ONSITEDATETO2, TW.ONSITETIMETO2
	        , TW.TOTAL_ONSITEDAY, TW.TOTAL_ONSITETIME, TW.SITESERVICE, TW.ONSITESTATUS
	        , TW.APPROVERID, TW.APPROVETS, TW.SITESERVICE_REMARK, TW.ONSITESTATUS_REMARK 
	    FROM TAD_WORKONSITE_HISTORY TW 
	        LEFT JOIN EMP_MEMBER EM ON EM.EMPLOYEEID = TW.EMPLOYEEID
	        LEFT JOIN SEC_USER SU ON SU.EMPLOYEEID = EM.EMPLOYEEID
	    WHERE SU.USERID IS NOT NULL
	    	AND SU.STATUS <> 'I' -- ไม่เอา user ที่ลาออก
	    	AND TW.WORKONSITEID = 23 -- Fix ประเภทหยุดชดเชย
			AND TW.ONSITESTATUS IN ('A', 'W')
	        AND CASE WHEN TW.UPDATETS IS NOT NULL THEN TW.UPDATETS ELSE TW.INPUTTS END >= %s -- '20100101000000'
	    	AND SU.USERID = %s -- กรณีที่ต้องการดึงเป็นรายบุคคล
	) A
	ORDER BY A.ONSITEID
}
