
package com.cct.hrmdata.web.getdatauser.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetUserWebServiceService", targetNamespace = "http://ws.getdatauser.web.hrmdata.cct.com/", wsdlLocation = "http://10.100.10.233:8080/hrm_webservice/GetUserWebService?wsdl")
public class GetUserWebServiceService
    extends Service
{

    private final static URL GETUSERWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException GETUSERWEBSERVICESERVICE_EXCEPTION;
    private final static QName GETUSERWEBSERVICESERVICE_QNAME = new QName("http://ws.getdatauser.web.hrmdata.cct.com/", "GetUserWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.100.10.233:8080/hrm_webservice/GetUserWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETUSERWEBSERVICESERVICE_WSDL_LOCATION = url;
        GETUSERWEBSERVICESERVICE_EXCEPTION = e;
    }

    public GetUserWebServiceService() {
        super(__getWsdlLocation(), GETUSERWEBSERVICESERVICE_QNAME);
    }

    public GetUserWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETUSERWEBSERVICESERVICE_QNAME, features);
    }

    public GetUserWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, GETUSERWEBSERVICESERVICE_QNAME);
    }

    public GetUserWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETUSERWEBSERVICESERVICE_QNAME, features);
    }

    public GetUserWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetUserWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetUserWebService
     */
    @WebEndpoint(name = "GetUserWebServicePort")
    public GetUserWebService getGetUserWebServicePort() {
        return super.getPort(new QName("http://ws.getdatauser.web.hrmdata.cct.com/", "GetUserWebServicePort"), GetUserWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetUserWebService
     */
    @WebEndpoint(name = "GetUserWebServicePort")
    public GetUserWebService getGetUserWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.getdatauser.web.hrmdata.cct.com/", "GetUserWebServicePort"), GetUserWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETUSERWEBSERVICESERVICE_EXCEPTION!= null) {
            throw GETUSERWEBSERVICESERVICE_EXCEPTION;
        }
        return GETUSERWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
