searchAdminInSystem {
	SELECT 
		SA.ADMIN_ID, SA.USER_ID, SA.SYSTEM_CODE, CONCAT(SU.NAME, ' (', SU.NICKNAME, ')') AS DISPLAY_NAME
		, SU.EMAIL, SU.GMAIL, SU.LINE_USER_ID
	FROM [SCHEMAS].sec_admin SA, [SCHEMAS].sec_user SU
	WHERE SA.USER_ID = SU.USER_ID
	AND SA.ACTIVE = 'Y'
	AND SA.SYSTEM_CODE = 'BK'
}

searchUserInSystem {
	SELECT 
		USER_ID, DEPARTMENT_ID, POSITION_ID
		, TITLE_NAME, NAME, SURNAME, NICKNAME, CONCAT(NAME, ' (', NICKNAME, ')') AS DISPLAY_NAME
		, EMAIL, GMAIL, LINE_USER_ID
		, COLOR_CODE, TABLE_NO, INSIDE_PHONE_NUMBER
		, CARD_ID ,LINE_DISPLAY_NAME,DATE_FORMAT(UPDATE_DATE, '%Y%m%d%h%i%S') AS UPDATE_DATE
	FROM [SCHEMAS].sec_user
	WHERE DELETED = 'N'
	AND USER_ID = %s
}


searchUserLogin{
	SELECT 
		USER_ID, DEPARTMENT_ID, POSITION_ID
		, TITLE_NAME, NAME, SURNAME, NICKNAME, CONCAT(NAME, ' (', NICKNAME, ')') AS DISPLAY_NAME
		, EMAIL, GMAIL, LINE_USER_ID
		, COLOR_CODE, TABLE_NO, INSIDE_PHONE_NUMBER
		, CARD_ID ,LINE_DISPLAY_NAME,DATE_FORMAT(UPDATE_DATE, '%Y%m%d%h%i%S') AS UPDATE_DATE
	FROM [SCHEMAS].sec_user
	WHERE DELETED = 'N'
	AND EMAIL = CONCAT(%s, '@somapait.com')
	AND CARD_ID = %s
}


updateLineDisplayName{
	UPDATE [SCHEMAS].sec_user
	SET LINE_DISPLAY_NAME = %s ,
	UPDATE_DATE  = SYSDATE()
	WHERE DELETED = 'N'
	AND USER_ID = %s
}

searchAuthorizationNormal {
	SELECT GROUP_ID, OPERATOR_ID, CREATE_DATE, CREATE_BY 
	FROM [SCHEMAS].sec_map_group_operator
	WHERE GROUP_ID = 5
}




